const CONF = {
	"FILE_STATE_MODIFIED_PREFIX": '__GH__FILE__MODIFIED__STATE__',
	"FILE_STATE_DELETION_PREFIX": '__GH__FILE__DELETION__STATE__',
	"FILE_STATE_CREATED_PREFIX":'__GH__FILE__CREATED__STATE__'
}

module.exports = CONF;